version: '2'
services:
  ms-config:
    image: 192.168.43.217/sky/skycloud-core-config
    ports:
      - "8888:8888"
    volumes:
      - /www/data/cloud/config:/www/data/cloud/config
    environment:
      - JVM_OPTS=-Xmx256m -Xms256m -XX:MaxPermSize=512m
      - BOOT_ARGS=${CONFIG_BOOT_ARGS}
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - front-tier
      - back-tier

  ms-eureka:
    image: 192.168.43.217/sky/skycloud-core-eureka
    ports:
      - "8761:8761"
    depends_on:
      - ms-config
    entrypoint: ./wait-for-it.sh ms-config:8888 -t 600 --
    command: java -Djava.security.egd=file:/dev/./urandom ${EUREKA_BOOT_ARGS} -jar ms-eureka.jar
    environment:
      - JVM_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=512m
      #- BOOT_ARGS=-DCONFIG_SERVICE_URL=http://10.28.60.163:8888
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - back-tier

  ms-monitor:
    image: 192.168.43.217/sky/skycloud-core-monitor
    ports:
      - "8788:8788"
    depends_on:
      - ms-eureka
    environment:
      - JVM_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=512m
      - BOOT_ARGS=${MONITOR_BOOT_ARGS}
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - front-tier
      - back-tier

  ms-dashboard:
    image: 192.168.43.217/sky/skycloud-core-dashboard
    ports:
      - "8789:8789"
    depends_on:
      - ms-config
      - ms-eureka
    entrypoint: ./wait-for-it.sh ms-config:8888 -t 600 --
    command: java -Djava.security.egd=file:/dev/./urandom ${DASHBOARD_BOOT_ARGS} -jar ms-dashboard.jar
    environment:
      - JVM_OPTS=-Xmx256m -Xms256m -XX:MaxPermSize=512m
      - TZ=Asia/Shanghai
    networks:
      - front-tier
      - back-tier

  ms-turbine:
    image: 192.168.43.217/sky/skycloud-core-turbine
    ports:
      - "8778:8778"
    depends_on:
      - ms-config
      - ms-eureka
    entrypoint: ./wait-for-it.sh ms-config:8888 -t 600 --
    command: java -Djava.security.egd=file:/dev/./urandom ${TURBINE_BOOT_ARGS} -jar ms-turbine.jar
    environment:
      - JVM_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=512m
      - TZ=Asia/Shanghai
    networks:
      - front-tier
      - back-tier

  ms-zipkin:
    image: 192.168.43.217/sky/skycloud-core-zipkin
    ports:
      - "9411:9411"
    depends_on:
      - ms-config
      - ms-eureka
    entrypoint: ./wait-for-it.sh ms-config:8888 -t 600 --
    command: java -Djava.security.egd=file:/dev/./urandom ${ZIPKIN_BOOT_ARGS} -jar ms-zipkin.jar
    environment:
      - JVM_OPTS=-Xmx512m -Xms512m -XX:MaxPermSize=512m
      - TZ=Asia/Shanghai
    networks:
      - front-tier
      - back-tier

networks:
  front-tier:
    driver: bridge
  back-tier:
    driver: bridge
